apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend-deployment
  namespace: monitoring-project

spec:
  replicas: 2

  selector:
    matchLabels:
      app: frontend-app

  template:
    metadata:
      labels:
        app: frontend-app

    spec:
      containers:
      - name: frontend-app
        image: kamal7b/frontend-app:v1

        ports:
        - containerPort: 3000

